add winamp default shortcuts
xmms2/promoe pull request #4
Opened 2021-07-01 16:46 UTC by soleuu

Hello,

I have added winamp default shortcuts. 
- z : previous track
- x : play
- c : pause
- v : stop
- b : next track
- n : open

I'm having problem adding media button, I have tried those constant with no luck :
      Key_MediaTogglePlayPause
      Key_MediaPause
      Key_MediaPlay
      Key_MediaStop
      Key_Play
      Key_Stop

Is there someone who can help me ?

I'm using ubuntu 20.04.

thank you.

2021-07-02 13:59 UTC, Malvineous requested changes
It looks fine to me apart from a few minor code style differences (not matching the existing coding style).  I don't mind merging it if these are fixed.

Can't help with the media keys though.  Personally I use my own xmms2hotkey client which makes the media keys work globally, no matter what app you're in.

2021-07-02 13:59 UTC, Malvineous commented on src/mainwindow/maindisplay.cpp
> +	connect (shortcut_eject, SIGNAL(activated()), this, SLOT(fileOpen()));
Missing spaces before `(` (e.g. `SIGNAL(` -> `SIGNAL (`, `activated()` -> `activated ()`, etc.)

2021-07-02 13:59 UTC, Malvineous commented on src/playlist/playlistwidget.cpp
> +QShortcut *shortcut_prev = new QShortcut(QKeySequence("z"), this);
Different indent

2021-07-02 13:59 UTC, Malvineous commented on src/playlist/playlistwidget.cpp
> +
Too many blank lines

2021-07-02 13:59 UTC, Malvineous commented on src/mainwindow/maindisplay.cpp
> +
Extra blank line

2021-07-02 16:35 UTC, soleuu commented on src/mainwindow/maindisplay.cpp
> +	connect (shortcut_eject, SIGNAL(activated()), this, SLOT(fileOpen()));
patched

2021-07-02 16:35 UTC, soleuu commented on src/playlist/playlistwidget.cpp
> +QShortcut *shortcut_prev = new QShortcut(QKeySequence("z"), this);
patched

2021-07-02 16:35 UTC, soleuu commented on src/mainwindow/maindisplay.cpp
> +
patched

2021-07-03 01:06 UTC, Malvineous commented
Thanks for the contribution!  Merged in 8c05cd58b922d77dcb50e29556992d3191f0a62e

2021-07-03 01:06 UTC, closed without merging

2021-07-03 07:02 UTC, soleuu commented
Thank you.
I will look for your xmms2hotkey for media button, thank you for the suggestion.
Have a nice day.